### ISSUE TITLE
Java export of PIDSubsystem is broken

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/RobotBuilder#104]
See Brads comment on https://github.com/wpilibsuite/RobotBuilder/pull/95#issuecomment-388657774

**Comment by bradamiller** [comment]
Which comment, and is it the returnPIDInput() method issue?

**Comment by sciencewhiz** [comment]
Yes it's the returnpidinput issue. I couldn't figure out how to link to a specific comment.

**Comment by sciencewhiz** [comment]
Thanks to Sam, I've now updated the link to the specific comment

**Comment by sciencewhiz** [comment]
Fixed by #118
