### ISSUE TITLE
RobotBuilder with vs code

### ISSUE THREAD

**Issue by idoavny** [wpilibsuite/RobotBuilder#111]
can i use it with vs code?, how do i open the robot builder?

**Comment by ThadHouse** [comment]
The alpha release does not have it integrated yet. You will need to open the version from eclipse. The season release will have it in the Run Tool menu item.

**Comment by idoavny** [comment]
wow a quick reply, thx i will try to do it now

**Comment by idoavny** [comment]
also i couldnt find a way to add subsystems to the code directly from the vs

**Comment by ThadHouse** [comment]
If you right click on the folder where you want to create a command, one of the options will be `Create a Command`

**Comment by sciencewhiz** [comment]
Closing as 2019 has been released which supports vscode
