### ISSUE TITLE
project templates need to be updated to match Eclipse Plugins

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/RobotBuilder#13]
The Eclipse project templates in Eclipse Plugins have several updates made since 2016 that need to be ported to RobotBuilder.

**Comment by sciencewhiz** [comment]
Since Eclipse autoupdates the projects, I'm not sure whether this is necessary anymore.

**Comment by nollchr** [comment]
What about updating project file to add include and libraries from "user" area of newly split off libraries such as CANTalon?  Will the project file generated have the appropriate include path and library path for "user" libraries such as CTR CANTalon?

**Comment by sciencewhiz** [comment]
The eclipse auto updater handles this.
