### ISSUE TITLE
Needs a rewrite for new Command-Based and PIDController

### ISSUE THREAD

**Issue by Daltz333** [wpilibsuite/RobotBuilder#146]
https://github.com/wpilibsuite/allwpilib/pull/1682 and https://github.com/wpilibsuite/allwpilib/pull/1300 make major changes to the existing Command-Based and PIDController system. RobotBuilder needs to be updated to reflect this.

**Comment by Nico1999** [comment]
I'm willing to take this on. I'll start working the changes in on my fork.

**Comment by cpapplefamily** [comment]
I have been taking a poke at the New Command Based (Java) export of RobotBuilder. I have a few hours into it. I forked from @Nico1999 so hopfully he can or some one else can use the bits to get the CPP side done. Truthfully I have no clue to the CPP side but the Java side is comming along well. Two Questions I came across thus far:

1. When I open the project I get a warning saying This Project is not compatible with this version of the extension. Please...  I assume its something to do with a config file of some sort in the RB exporter 

2. With the Command Needing to know what Subsystem it requires as a parameter into its constructor I'm finding it difficult to parse the object Name. The current Code snip `#variable(${command.getProperty("Requires").getValue()})` returns the object name but not the Class Name that will be needed to assign the parameter type. 
`public ExampleCommand(ExampleSubsystem subsystem) {
    m_subsystem = subsystem;
    addRequirements(subsystem);`
I'm thinking about adding a parameter to the ExportDescription and a getter macro for `objectName: "#class($Short_Name)"`

I already added a parameter `NewObject: "private final .....` to create a field that will declare and construct the objects on one line like most of the examples have.

 
![Project is not compatible](https://user-images.githubusercontent.com/16618289/67144304-c04ff000-f23a-11e9-928b-aede08f1f9fd.PNG)

**Comment by cpapplefamily** [comment]
> When I open the project I get a warning saying This Project is not compatible with this version of the extension. Please... I assume its something to do with a config file of some sort in the RB exporter

Fixed that in the wpilib_preferences.json `"projectYear": "Beta2020",`

**Comment by cpapplefamily** [comment]
> 2\. With the Command Needing to know what Subsystem it requires as a parameter into its constructor I'm finding it difficult to parse the object Name. The current Code snip `#variable(${command.getProperty("Requires").getValue()})` returns the object name but not the Class Name that will be needed to assign the parameter type.
>     `public ExampleCommand(ExampleSubsystem subsystem) { m_subsystem = subsystem; addRequirements(subsystem);`
>     I'm thinking about adding a parameter to the ExportDescription and a getter macro for `objectName: "#class($Short_Name)"`

After hacking through it I found a better way so I removed my new variables objectName, objectType.

**Comment by sciencewhiz** [comment]
#155 will be merged for beta 2, which will probably cause some minor conflicts in your work.

**Comment by sciencewhiz** [comment]
Unfortunately, there's still too much work on porting RobotBuilder to support the New Command Framework for the 2020 season officially. However, @cpapplefamily 's work has been merged to the NewCommandFramework branch and PRs are welcome against that branch.
