### ISSUE TITLE
Add RobotBuilder to usage reporting

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/RobotBuilder#147]

**Comment by bradamiller** [comment]
Was the plan to generate an instantiation of some class that could be tracked?

**Comment by sciencewhiz** [comment]
TimedRobot already reports TimedRobot in the constructor. What happens if RobotBuilder also adds a call that reports RobotBuilder? Is that OK, or does RobotBuilder have to make sure that TimedRobot doesn't get reported?

**Comment by bradamiller** [comment]
I'd think we want to do both so we can track timed robot usage apart from RobotBuilder.

**Comment by sciencewhiz** [comment]
I mean, how does the usage reporting system handle getting conflicting values?
