### ISSUE TITLE
Maybe not an issue, but definitely a question. About Talon SRX and Brushless Sparks

### ISSUE THREAD

**Issue by mddrouillard** [wpilibsuite/RobotBuilder#161]
Hello foks, I noticed in version 2.0 of RobotBuilder the interface allows for CAN ID connected TalonSRX speed controllers. This is the version currently launched from within VSCODE tools menu. However the current buildable version seems only to have PWM connected speed controllers. We have used RobobotBuilder to build code frames for the New RevRobotics Spark Max brushless motors, by using the TalonSRX motors, and substituting in the code in place after export. 

So, 2 questions, Where has the Talon SRX Can ID based options gone, and is there any plans to add in RevRobotics Spark Max CanID based controllers into the code base. How would I add it if I wanted to do so myself?

Many thanks.
Mddrouillard@gmail.com

**Comment by sciencewhiz** [comment]
Robotbuilder by itself only supports items built into wpilib. However, it has an extensions interface to allow people to add items. CTRE distributes an extension for the TalomSRX and other products. To my knowledge, Rev Robotics does not publish an extension for the Spark Max. You can read about how to create an extension here: https://wpilib.screenstepslive.com/s/currentCS/m/robotbuilder/l/470258-adding-custom-components

For 2020, the location of the extensions is changing and that was merged a few days ago. https://github.com/wpilibsuite/RobotBuilder/issues/126

If you aren't a beta team, you should continue using last years version of Robotbuilder.
