### ISSUE TITLE
Implement C++ New Commands

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/RobotBuilder#191]

**Comment by sciencewhiz** [comment]
Are you interested specifically in support of the new command framework for C++ (this issue) or Java? The java implementation is available in the NewCommandFramework branch. You can file bugs with the New Commands label.

**Comment by bovlb** [comment]
I'm primarily interested in Java.  (Sorry, this issue was the most appropriate I could see, and there are no other contact details posted.)  I am trying out the branch now.
