### ISSUE TITLE
Java Runtime Version Error

### ISSUE THREAD

**Issue by xeu100** [wpilibsuite/RobotBuilder#197]
Error:
```
* What went wrong:
java.lang.UnsupportedClassVersionError: edu/wpi/first/wpilib/versioning/WPILibVersioningPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> edu/wpi/first/wpilib/versioning/WPILibVersioningPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
 ```
 
Java Version:
```
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) Client VM (build 25.241-b07, mixed mode, sharing)
```
Running JDK 1.8.0_221

Full Stacktrace:
https://paste.xeu100.com/?9d80d2ad6a01fa37#9jwYQxbEWL9bnQ+QHkKoEFuhhWHHmFzznNpsXEeu450=

**Comment by PeterJohnson** [comment]
All of the tools require Java 11.  This is installed as part of the overall WPILib installer (see https://github.com/wpilibsuite/allwpilib/releases and the installation instructions here https://docs.wpilib.org/en/latest/docs/getting-started/getting-started-frc-control-system/wpilib-setup.html).
