### ISSUE TITLE
Command group issues 

### ISSUE THREAD

**Issue by Nerf12402** [wpilibsuite/RobotBuilder#206]
In the Robotbuilder interface, when trying to edit a command group, the screen to set up the commands in order doesn't show up. You can't add any commands to a command group.

**Comment by sciencewhiz** [comment]
From http://docs.wpilib.org/en/latest/docs/software/wpilib-overview/new-for-2020.html#robotbuilder
> GUI for defining Command Groups was removed for maintainability reasons. Commands can be added in VS Code.
