### ISSUE TITLE
Use default browser to launch help

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/RobotBuilder#230]
Right now, the help is launched on start-up using firefox https://github.com/wpilibsuite/RobotBuilder/blob/master/src/main/java/robotbuilder/Utils.java#L86 

It should be launched with https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/java/awt/Desktop.html#browse(java.net.URI) to launch with the default browser.

**Comment by Starlight220** [comment]
It seems that it starts by launching the default browser, and uses firefox only in the `catch` clause. What should be changed here?
