### ISSUE TITLE
Setpoint command Parameter Presets fails to populate with Required Subsystems Constants

### ISSUE THREAD

**Issue by cpapplefamily** [wpilibsuite/RobotBuilder#277]
The Parameter Presets for a Setpoint command does list the constants of the selected required subsystem but when chosen it does not populate the drop down selector. The selector seems to only except numbers. Not strings such as PIDSubsystem1.Up where Up is a constant of the PIDSubsystem 1.

**Comment by sciencewhiz** [comment]
This appears to be broken by Java 11. I went back to a07aa9b324304a which is the last version that could run with Java 8. It works in Java 8 and fails in Java 11.
