### ISSUE TITLE
Pre-existing user-written code is deleted when generating code

### ISSUE THREAD

**Issue by SamCarlberg** [wpilibsuite/RobotBuilder#29]
[Reported by tomy on ChiefDelphi](https://www.chiefdelphi.com/forums/showthread.php?t=153263)

Before:

![before](https://cloud.githubusercontent.com/assets/6320992/21757426/7e4a9fe6-d5fc-11e6-8b56-0ac646c76423.PNG)

After:
![after](https://cloud.githubusercontent.com/assets/6320992/21757427/815ea5a6-d5fc-11e6-8e89-16c4c76f38a6.PNG)

**Comment by sciencewhiz** [comment]
I can't duplicate this

**Comment by SamCarlberg** [comment]
I'm thinking [this answer](https://www.chiefdelphi.com/forums/showpost.php?p=1627598&postcount=6) is right on the money. I just opened this issue so we'd have parity.
