### ISSUE TITLE
Crash when opening 2020 file with Timed Command

### ISSUE THREAD

**Issue by jmullins16** [wpilibsuite/RobotBuilder#325]
Opening our 2020 robot file causes a Java crash for commands that were removed in 2021 RobotBuilder--probably for the new Command-based structure. Timed Command and Command Group were both used in our 2020 robot, but caused crashes until we cut them out of the file. It needs to be at least more graceful than a crash, and preferably just omit those sections with some sort of notification.

**Comment by sciencewhiz** [comment]
Robotbuilder should keep you from opening an old project in the new version. Besides the different commands, the frameworks are different enough that even for commands that have the same name that the code gen would be broken. 

The check is working opening a new file in old RobotBuilder but not vice versa.
