### ISSUE TITLE
Generated putData() of commands needs to add .withName()

### ISSUE THREAD

**Issue by bradamiller** [wpilibsuite/RobotBuilder#355]
RobotBuilder generates SmartDashboard buttons for created commands using code like this:
    SmartDashboard.putData("Forward: OneFoot", new Forward(12, m_chassis));

The .withName() decorator should be added so that it's displayed correctly in glass and shuffleboard like this:
    SmartDashboard.putData((CommandBase) (new Turn(m_romiDrivetrain, 90).withName("Turn 90")));

**Comment by sciencewhiz** [comment]
Here's what I get for this line in smartdashboard and shuffleboard:
`SmartDashboard.putData("Set Wrist Setpoint: Horizontal", new SetWristSetpoint(0, m_wrist));`

SmartDashboard:
![image](https://user-images.githubusercontent.com/4885091/103849355-50a16d00-5059-11eb-9b8a-90a328e2f6c3.png)
Shuffleboard:
![image](https://user-images.githubusercontent.com/4885091/103849425-79296700-5059-11eb-8ed0-d9279cc101a4.png)

I think Glass would show the name if there was room in the window

![image](https://user-images.githubusercontent.com/4885091/103849885-bfcb9100-505a-11eb-925d-ea1949a73193.png)

**Comment by bradamiller** [comment]
It is using the command name and not the label. The problem I had was that I had two turn commands on the dashboard, one was called "turn 90" and the other was "turn -90", but they both displayed ambiguously as "Turn" because glass used the command name and not the putData first parameter.

**Comment by sciencewhiz** [comment]
When wpilibsuite/allwpilib#3060 is resolved, then the Glass display would be similar to the Shuffleboard display

**Comment by sciencewhiz** [comment]
In Glass 2021.2.1, the key is shown first, obviating this issue.

**Comment by sciencewhiz** [comment]
Closing since glass now shows the name
