### ISSUE TITLE
Robotbuilder fails to load existing yml file.

### ISSUE THREAD

**Issue by danielcastellarin** [wpilibsuite/RobotBuilder#36]
We have one laptop using plugins version 2017.2.1 and one using 2017.1.1.  The 2.1 version fails to load yml save file.  The 1.1 works. When opening thru eclipse we get no output/result until we exit eclipse. Then exception/error window pops up.  If we open Robotbuilder directly same thing happens after choosing to load existing project.
![robotbuilder_exception](https://cloud.githubusercontent.com/assets/25212372/22620760/a9619484-eae0-11e6-990d-88819d6bcf8f.PNG)

Our Robotbuilder.yml file can be found here: https://github.com/BHSRobotix/Steamworks2017/blob/master/RobotBuilder.yaml

**Comment by sciencewhiz** [comment]
Have you installed the CTRE toolsuite on the laptop that fails? Your yaml references CAN Talon, which is an extension installed by the CTRE toolsuite.

**Comment by chriscostello9** [comment]
Yep. that was the problem(same team that opened this issue posting from different user/laptop). Thanks for the tip.
