### ISSUE TITLE
C++ XBoxController button export still wrong

### ISSUE THREAD

**Issue by jmullins16** [wpilibsuite/RobotBuilder#377]
It exports this:
frc2::JoystickButton m_xboxButton1{&m_xboxController1, (int)frc::XboxController::Button::B};

and I think it should be this:
frc2::JoystickButton m_xboxButton1{&m_xboxController1, (int)frc::XboxController::Button::kB};

Looks like the bug fix addressed the prefixed class names, but not the actual enum.

**Comment by sciencewhiz** [comment]
It looks like there was a problem with the test, so it wasn't actually compiling with Xbox Button
