### ISSUE TITLE
C++ Removing a required subsystem overwrites the entire command file

### ISSUE THREAD

**Issue by jmullins16** [wpilibsuite/RobotBuilder#381]
We removed a required subsystem from a command, and the entire command file was changed back to the initial template--not just the constructor.

**Comment by sciencewhiz** [comment]
I can't duplicate this

**Comment by jmullins16** [comment]
Maybe our YAML file has a problem.

https://github.com/usfirst-frc-2135/software/blob/dev/2021/Robot2021.yaml

In order to export this, it will require adding the Phoenix library and commenting out the Xbox button hooks in RobotContainer. (Build)

Add a line of code to ClimberRun in the Initialize method. (Build)

Change ClimberRun Requires setting to None.

Code is missing. Hope this helps.

**Comment by sciencewhiz** [comment]
I was able to reproduce it with your file. The issue is that Robotbuilder is picking up the parameter as a type, but only when there isn't a required subystem. So it think the type is changing which causes the overwrite.
