### ISSUE TITLE
Comment error in Robot.java generated by RobotBuilder

### ISSUE THREAD

**Issue by AustinShalit** [wpilibsuite/RobotBuilder#42]
_From @jee7s on May 19, 2017 3:20_

In the referenced file, there is a comment that reads, in part:

> If you change the name of this class or the package after creating this project, you must also update the manifest file in the resource directory.

We found the location of the package and class definitions to be in the project's build.properties file, not the manifest file. Could this comment be updated for clarity?

_Copied from original issue: wpilibsuite/allwpilib#541_

**Comment by AustinShalit** [comment]
https://github.com/wpilibsuite/RobotBuilder/blob/master/src/main/resources/export/java/RobotTemplate.java#L12-L18

**Comment by sciencewhiz** [comment]
This affects the eclipse plugins also.
