### ISSUE TITLE
Run tidy on html files

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/RobotBuilder#72]

**Comment by JLLeitschuh** [comment]
Tidy could be integrated into spotless with jtidy.
https://mvnrepository.com/artifact/net.sf.jtidy/jtidy/r938

**Comment by JLLeitschuh** [comment]
https://github.com/diffplug/spotless/issues/162

**Comment by sciencewhiz** [comment]
jtidy seems quite old. #73 fixed this for the short term, hopefully with code review, it won't degrade much
