### ISSUE TITLE
Gradle depencies change warning

### ISSUE THREAD

**Issue by sciencewhiz** [wpilibsuite/RobotBuilder#9]
Gradle build warns about changed dependencies.

Changed dependencies of configuration ':lombok' after it has been included in dependency resolution. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0.
Changed dependencies of parent of configuration ':compile' after it has been resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0

**Comment by PeterJohnson** [comment]
Fixed by #70.
