### ISSUE TITLE
gradlew doesn't recognize java 9.0.4

### ISSUE THREAD

**Issue by jerseyjohn365** [wpilibsuite/RobotBuilder#99]
running "gradlew shadowjar" - "could not determine java version from 9.0.4'

**Comment by JLLeitschuh** [comment]
I don't think that any of the wpilibsuite tools/libraries have been tested with Java 9.
I'd recommend installing JDK 8 on your system and trying to build with that.

**Comment by ThadHouse** [comment]
Closed by b30d96646d74df0204288449ab2046209c257420
